title: DevOps Journey
description: Coleção de recursos que me ajudaram ao longo da minha jornada profissional.
author: Bruno Feliano

baseurl: "/devops-journey"
url: "https://bfeliano.github.io"

markdown: kramdown

social:
  github: https://github.com/bfeliano
  linkedin: https://www.linkedin.com/in/brunofeliano
