name: Lint

on: [pull_request]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v16
      with:
        config: 'config/.markdownlint.json'
        globs: '**/*.md'
